### ISSUE TITLE
如何查看指定分支的代码

### ISSUE THREAD

**Issue by lilywang711** [niudai/Github-Explorer#15]
例如 https://github.com/ant-design/v2.preview.pro.ant.design 这个仓库，它默认只有 v2 分支，当去使用 remote-github 时会报错
![image](https://user-images.githubusercontent.com/17040010/84129498-9cb11280-aa74-11ea-89ec-c41de2f690ff.png)
![image](https://user-images.githubusercontent.com/17040010/84129518-a3d82080-aa74-11ea-894a-831de28cc324.png)

**Comment by niudai** [comment]
因为默认使用的是 master，如果没有 master 分支，就 "https://github.com/ant-design/v2.preview.pro.ant.design  -b v2"

**Comment by lilywang711** [comment]
谢谢
