### ISSUE TITLE
在输入登陆用户密码之后长时间卡在登陆途中，并且logging in拼错

### ISSUE THREAD

**Issue by Toni-Chan** [niudai/Github-Explorer#5]
![image](https://user-images.githubusercontent.com/18144686/83454626-7531c880-a42a-11ea-8fc7-caed22a49cb7.png)
密码错误的时候应该给一个提示更合适，现在的状态是卡在logging in界面

**Comment by Toni-Chan** [comment]
不知道登陆机制是否使用了额外的port channel，这台是公司用电脑所以可能限制了一些port的使用

**Comment by niudai** [comment]
好的，下个版本解决
