### ISSUE TITLE
Supports to jumps to definitions implementation code section when click somewhat method or variables

### ISSUE THREAD

**Issue by qqcome110** [niudai/Github-Explorer#7]
The issue on this title

**Comment by niudai** [comment]
supported in 0.2

**Comment by qqcome110** [comment]
It doesn't seem to be working

**Comment by niudai** [comment]
see what's new in CHANGELOG


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lenq"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月9日(星期二) 下午4:23
收件人:&nbsp;"niudai/Github-Explorer"<Github-Explorer@noreply.github.com&gt;;
抄送:&nbsp;"阿克希亚"<1244453736@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [niudai/Github-Explorer] Supports to jumps to definitions implementation code section when click somewhat method or variables (#7)





 
It doesn't seem to be working

**Comment by qqcome110** [comment]
I see. I'm sorry. It's ready working now
